workflows:
  my-workflow:
    scripts:
      - name: Build Android APK
        working_directory: android
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/**/*.apk
workflows:
  my-workflow:
    triggering:
      events:
        - push
      branch_patterns: 
        - pattern: dev
        - pattern: develop
          include: false
      cancel_previous_builds: true
      

